output "cluster_id" {
  description = "eks cluster id"
  value       = module.wfa_eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for eks control plane."
  value       = module.wfa_eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.wfa_eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.wfa_eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.wfa_eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}
