# Copyright 2021 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run Kubernetes-in-Docker tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cross-media-measurement:
    name: Build and test cross-media-measurement targets
    runs-on: ubuntu-20.04
    steps:
      - name: Check out revision
        uses: actions/checkout@v2

      - name: Install Kubernetes-in-Docker
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.10.0
          skipClusterCreation: true

      - name: Bazel build and test
        uses: world-federation-of-advertisers/actions/bazel-build-test@main
        with:
          workspace-path: ${{ github.job }}
          target-patterns: |
            src/test/kotlin/org/wfanet/measurement/e2e:correctness_test
