# This workflow will build a Bazel project using Bazelisk.

name: Build and run all targets in cross-media-measurement

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cross-media-measurement

    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Set execroot hash
      run: |
        execroot_hash="$(
          bazelisk info execution_root | tr -d '\n' | git hash-object --stdin
        )"
        echo "execroot_hash=${execroot_hash}" >> $GITHUB_ENV

    - name: Set output base path
      run: echo "output_base_path=$(bazelisk info output_base)" >> $GITHUB_ENV

    - name: Set tree hash
      run: echo "tree_hash=$(git rev-parse HEAD:)" >> $GITHUB_ENV

    - name: Set up build cache
      uses: actions/cache@v2
      with:
        path: ${{ env.output_base_path }}
        key: bazel-${{ env.execroot_hash }}-${{ env.tree_hash }}
        restore-keys: |
          bazel-${{ env.execroot_hash }}-

    - name: Build
      run: bazelisk build --keep_going //...

    - name: Test
      run: bazelisk test --keep_going //...

    - name: Copy test logs
      if: failure()
      run: cp -Lr "$(bazelisk info bazel-testlogs)" "$HOME/bazel-testlogs"

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs
        path: ~/bazel-testlogs/
