# This workflow will build a Bazel project using Bazelisk.

name: Build and run all targets in cross-media-measurement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cross-media-measurement

    steps:
    - name: Check out revision
      uses: actions/checkout@v2

    - name: Set up build cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/bazel
        key: bazel-xmms-${{ hashFiles('cross-media-measurement/WORKSPACE') }}
        restore-keys: |
          bazel-xmms-
          bazel-

    - name: Build
      run: bazelisk build --keep_going //...

    - name: Test
      run: bazelisk test --keep_going //...

    - name: Copy test logs
      if: failure()
      run: cp -Lr "$(bazelisk info bazel-testlogs)" "$HOME/bazel-testlogs"

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs
        path: ~/bazel-testlogs/
